controller_list:
  - name: ""
    action_ns: arm_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [elbow_joint, shoulder_1_joint, shoulder_2_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]

